import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Filipe Cabral Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Filipe Cabral</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Filipe Cabral
            </h2>
            <h3 className="text-2xl py-2">Frontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I am looking for the right opportunity to develop my career as a
              Frontend Developer, so I've been studying and working daily on
              small projects
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} alt="me" layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services i offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur
              <span className="text-teal-500">adipisicing</span> elit.
              Voluptatum explicabo corrupti a in numquam suscipit minima ullam
              sunt cumque maxime, id tempora voluptate deserunt cupiditate
              <span className="text-teal-500">dolores</span> odio voluptates
              consectetur vitae saepe tenetur quae voluptatibus molestiae.
              Error, architecto eveniet.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
